### ISSUE TITLE
non thin tabs back

### ISSUE THREAD

**Issue by moonfight1** [nuclearcodecat/shimmer#25]
this is in 2.13 
![image](https://github.com/user-attachments/assets/9249ba3c-b5a4-4762-ab02-9e60c48af55a)
this is in 2.14
![image](https://github.com/user-attachments/assets/5b30bdba-4f86-451e-b28e-926ac3c708f1)

**Comment by nuclearcodecat** [comment]
bruh why it works fine for me. try disabling the config property that might be it and i added something unwated to it

**Comment by moonfight1** [comment]
setting `shimmer.dont-expand-selected-tab` to false didnt work

**Comment by nuclearcodecat** [comment]
sorry, got confused by the taller tabs that you have enabled. i changed the tabs to use `em` instead of `px` and they've got different dimensions now. i do agree that that they look a bit long, so i shortened them and released an update. download that and if you still don't like them, you can always modify these lines:
```
  /*? max tab width */
  --shimmer-tab-max-width: 13em;
  /*? min tab width */
  --shimmer-tab-min-width: 9em;
  /*? selected tab width */
  --shimmer-tab-selected-width: var(--shimmer-tab-max-width);
```

they're very near the top of `userChrome.css`
